version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - ./project:/var/www/html
#      - ./docker/entrypoint.sh:/var/www/html/entrypoint.sh
#      - ./docker/supervisord.conf:/var/www/html/supervisord.conf
#    entrypoint: ["sh", "/var/www/html/entrypoint.sh"]
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: horizon_test
      MYSQL_DATABASE: horizon_test
      MYSQL_USER: horizon_test
      MYSQL_PASSWORD: horizon_test
    ports:
      - "3309:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"